### ISSUE TITLE
Part 3 review

### ISSUE THREAD

**Issue by bgeta** [kellyhatfield/KellyHatfield-MADA-Project#2]
Hi Kelly, 
I enjoyed reviewing your project. I think your instructions in the README files are intuitive. Also, appreciate the addition of the code books in the raw data folder. I did not run into errors while running your codes. I was also able to render your manuscript although I am not sure if it's the most updated. I think you could update section 3 of your document. There are some tables and graphs (E.g. Table 1 and graph 1)  that could be updated as well. I think your study was replicable. (Btw I really like your topic). 
I gave a score of 3.

Thanks
Betelihem G.

**Comment by kellyhatfield** [comment]
Thanks. I made some changes
